apiVersion: v1
kind: ConfigMap
metadata:
  name: imageviewing-properties
data:      
  imageviewing.properties: |
    #Application Details for Swagger Documentaion
    app.title=Viewing Rest Services
    app.description=To access Image viewing rest services, user should be authenticated & should have the scope PDN100.
    app.version=1.0.0.0
