apiVersion: v1
kind: Secret
metadata:
  name: secrets
  annotations:
    avp.kubernetes.io/path: "secret/data/sample-a"
    avp_path: secret/data/sample-a
type: Opaque
stringData:
  password: <password>
